// GENERATED by `npm run gen:declarations` from libs/test-config/src/process-termination-observer.mjs. DO NOT EDIT.
// Edits here are silently discarded on the next run — change the JSDoc in
// libs/test-config/src/process-termination-observer.mjs and regenerate.
/**
 * @typedef {{ phase: 'exit' | 'signal', exitCode: number | null, signal: 'SIGTERM' | 'SIGINT' | null }} Termination
 */
/**
 * Observe synchronously without replacing application signal handlers. SIGKILL
 * cannot be observed; absence of a receipt must remain unknown to consumers.
 * @param {(termination: Termination) => void} callback
 * @returns {void}
 */
export function observeProcessTermination(callback: (termination: Termination) => void): void;
export type Termination = {
    phase: "exit" | "signal";
    exitCode: number | null;
    signal: "SIGTERM" | "SIGINT" | null;
};
